version: '3'

services:
    server:
        build: ./hello_world
        container_name: web_server
    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - 80:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

